import type { Conviction, Direction, LevelRole } from "./scoring";

export const FEATURED_COHORT_SLUG = "2026-09-07";
export const LATEST_COHORT_SLUG = "2026-09-21";

export const SYMBOL_NAMES: Record<string, string> = {
  SPY: "S&P 500 ETF",
  QQQ: "Nasdaq 100 ETF",
  IWM: "Russell 2000 ETF",
  NVDA: "NVIDIA",
  AAPL: "Apple",
  MSFT: "Microsoft",
  TLT: "20+ Year Treasury ETF",
};

export type AccountSpec = {
  handle: string;
  displayName: string;
  bio: string;
  posture: string;
  accent: string;
};

export const ACCOUNTS: AccountSpec[] = [
  {
    handle: "gammagoblin",
    displayName: "Gamma Goblin",
    bio: "Demo account. Weekend gamma maps and call-wall stories.",
    posture: "Short-dated gamma",
    accent: "#0f766e",
  },
  {
    handle: "macromoth",
    displayName: "Macro Moth",
    bio: "Demo account. Slow macro, real yields, and leadership rolls.",
    posture: "Macro bear bias",
    accent: "#9a3412",
  },
  {
    handle: "tapeworm",
    displayName: "Tape Worm",
    bio: "Demo account. Opening drive and single-name supply.",
    posture: "Tape reader",
    accent: "#1d4ed8",
  },
  {
    handle: "dividenddruid",
    displayName: "Dividend Druid",
    bio: "Demo account. Adds quality on flushes and grinds.",
    posture: "Quality dip buyer",
    accent: "#3f6212",
  },
  {
    handle: "gapfade",
    displayName: "Gap Fade",
    bio: "Demo account. Fades the weekend gap back toward Friday.",
    posture: "Weekend fade",
    accent: "#6d28d9",
  },
  {
    handle: "volwidow",
    displayName: "Vol Widow",
    bio: "Demo account. Hedges first, direction second.",
    posture: "Convexity hedge",
    accent: "#9f1239",
  },
  {
    handle: "nasdaqnun",
    displayName: "Nasdaq Nun",
    bio: "Demo account. Megacap trend and leader targets.",
    posture: "Megacap long",
    accent: "#0e7490",
  },
  {
    handle: "creditcrab",
    displayName: "Credit Crab",
    bio: "Demo account. Sideways credit, cautious index risk.",
    posture: "Credit cautious",
    accent: "#b45309",
  },
  {
    handle: "futuresfox",
    displayName: "Futures Fox",
    bio: "Demo account. Cash levels mapped from the index future.",
    posture: "Index levels",
    accent: "#c2410c",
  },
  {
    handle: "yieldyak",
    displayName: "Yield Yak",
    bio: "Demo account. Rates path expressed through the long bond ETF.",
    posture: "Rates",
    accent: "#0369a1",
  },
  {
    handle: "smallcapsam",
    displayName: "Smallcap Sam",
    bio: "Demo account. Russell breadth and catch-up calls.",
    posture: "Small-cap beta",
    accent: "#4d7c0f",
  },
  {
    handle: "permapump",
    displayName: "Perma Pump",
    bio: "Demo account. Always long the index, same destination.",
    posture: "Perma bull",
    accent: "#a16207",
  },
  {
    handle: "doomscroll",
    displayName: "Doom Scroll",
    bio: "Demo account. Always short, crash magnets and wide stops.",
    posture: "Perma bear",
    accent: "#be123c",
  },
  {
    handle: "levellena",
    displayName: "Level Lena",
    bio: "Demo account. Magnet, shelf, and invalidation on every call.",
    posture: "Precise levels",
    accent: "#115e59",
  },
  {
    handle: "narrativened",
    displayName: "Narrative Ned",
    bio: "Demo account. Mood and narrative, rarely a number.",
    posture: "Vague narrative",
    accent: "#57534e",
  },
];

export type LevelSpec = {
  symbol: string;
  price: number;
  role: LevelRole;
};

export type CallSpec = {
  handle: string;
  direction: Direction;
  conviction: Conviction;
  primary: string;
  explicit: boolean;
  body: string;
  levels?: LevelSpec[];
  tickers?: string[];
};

export type QuoteSpec = {
  symbol: string;
  ref: number;
  monday: number | null;
  wednesday: number | null;
  friday: number | null;
};

export type CohortSpec = {
  slug: string;
  title: string;
  summary: string;
  monday: { year: number; month: number; day: number };
  isLatest?: boolean;
  quotes: QuoteSpec[];
  calls: CallSpec[];
};

const target = (symbol: string, price: number): LevelSpec => ({
  symbol,
  price,
  role: "target",
});
const invalidation = (symbol: string, price: number): LevelSpec => ({
  symbol,
  price,
  role: "invalidation",
});
const support = (symbol: string, price: number): LevelSpec => ({
  symbol,
  price,
  role: "support",
});
const resistance = (symbol: string, price: number): LevelSpec => ({
  symbol,
  price,
  role: "resistance",
});

/**
 * Demo prices are fictional. Each cohort is one collect window
 * (Wednesday 12:00 PM ET → Sunday 5:00 PM ET) graded on the following
 * Monday, Wednesday, and Friday at 12:00 PM ET. The latest cohort has
 * only the Monday grade published.
 */
export const COHORTS: CohortSpec[] = [
  {
    slug: "2026-08-24",
    title: "Hot CPI hangover",
    summary:
      "Weekend books mixed a hot inflation print with dip-buying. The same calls slid lower through Friday.",
    monday: { year: 2026, month: 8, day: 24 },
    quotes: [
      { symbol: "SPY", ref: 562, monday: 556.1, wednesday: 551.4, friday: 548.2 },
      { symbol: "QQQ", ref: 486.5, monday: 479.2, wednesday: 472.8, friday: 468.4 },
      { symbol: "IWM", ref: 221.4, monday: 217.1, wednesday: 213.6, friday: 210.8 },
      { symbol: "NVDA", ref: 131.2, monday: 126.4, wednesday: 122.1, friday: 118.6 },
      { symbol: "AAPL", ref: 228.4, monday: 225.1, wednesday: 222.4, friday: 220.1 },
      { symbol: "TLT", ref: 93.8, monday: 92.4, wednesday: 91.5, friday: 90.7 },
      { symbol: "MSFT", ref: 418, monday: 412.2, wednesday: 407.5, friday: 403.2 },
    ],
    calls: [
      {
        handle: "doomscroll",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Hot print, weekend longs are trapped. SPY 545 is the magnet. I am wrong only through 566.",
        levels: [target("SPY", 545), support("SPY", 547), invalidation("SPY", 566)],
      },
      {
        handle: "macromoth",
        direction: "bearish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "Real yields do the work. Nasdaq gives the squeeze back toward 470. Out above 490.",
        levels: [target("QQQ", 470), invalidation("QQQ", 490)],
      },
      {
        handle: "yieldyak",
        direction: "bearish",
        conviction: "medium",
        primary: "TLT",
        explicit: true,
        body: "The curve reprices the print. TLT 91 before anyone says slowdown. Invalid above 95.",
        levels: [target("TLT", 91), invalidation("TLT", 95)],
      },
      {
        handle: "levellena",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "550 is the magnet. I want 547 tested as a shelf. The short is dead above 565.",
        levels: [target("SPY", 550), support("SPY", 547), invalidation("SPY", 565)],
      },
      {
        handle: "futuresfox",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Sellers live above Friday's settle. Cash SPY rejects 563 and trades 552. Stop 566.",
        levels: [target("SPY", 552), resistance("SPY", 563), invalidation("SPY", 566)],
      },
      {
        handle: "volwidow",
        direction: "bearish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Own the downside convexity. Spot does not need a crash, just a trip through 555.",
        levels: [target("SPY", 555), invalidation("SPY", 566)],
      },
      {
        handle: "creditcrab",
        direction: "bearish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "Credit is quieter than equities admit. Small caps wear it first. IWM 212, wrong above 224.",
        levels: [target("IWM", 212), invalidation("IWM", 224)],
      },
      {
        handle: "permapump",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "The dip is a gift. 575 is still the upside magnet. I am out only if 558 goes.",
        levels: [target("SPY", 575), invalidation("SPY", 558)],
      },
      {
        handle: "nasdaqnun",
        direction: "bullish",
        conviction: "high",
        primary: "NVDA",
        explicit: true,
        body: "Leaders do not die on one CPI print. NVDA 140 this week. Wrong under 125.",
        levels: [target("NVDA", 140), invalidation("NVDA", 125)],
      },
      {
        handle: "gammagoblin",
        direction: "bullish",
        conviction: "medium",
        primary: "QQQ",
        explicit: true,
        body: "Call-wall squeeze through 490 into 495 if the Sunday reopen is firm. Cut under 480.",
        levels: [target("QQQ", 495), invalidation("QQQ", 480)],
      },
      {
        handle: "dividenddruid",
        direction: "bullish",
        conviction: "medium",
        primary: "AAPL",
        explicit: true,
        body: "Buy quality on the flush. Apple holds 224 and grinds to 232. I leave under 220.",
        levels: [target("AAPL", 232), support("AAPL", 224), invalidation("AAPL", 220)],
      },
      {
        handle: "smallcapsam",
        direction: "bullish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "Breadth catch-up. IWM 228 if the print was already priced. Invalid under 216.",
        levels: [target("IWM", 228), invalidation("IWM", 216)],
      },
      {
        handle: "narrativened",
        direction: "bullish",
        conviction: "low",
        primary: "SPY",
        explicit: false,
        body: "Feels like they want to buy any weakness. The soft-landing crowd is not leaving.",
      },
      {
        handle: "gapfade",
        direction: "bullish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "A Monday gap down gets faded back toward Friday's 564 area. I bail under 555.",
        levels: [target("SPY", 566), resistance("SPY", 564), invalidation("SPY", 555)],
      },
      {
        handle: "tapeworm",
        direction: "bearish",
        conviction: "medium",
        primary: "MSFT",
        explicit: true,
        body: "Supply sits in megacap software. Microsoft 405 if the open cannot reclaim. Stop 422.",
        levels: [target("MSFT", 405), invalidation("MSFT", 422)],
      },
    ],
  },
  {
    slug: "2026-08-31",
    title: "Pin week",
    summary:
      "A flat tape. Posture barely mattered. The call that named the pin was the one that cleared the line.",
    monday: { year: 2026, month: 8, day: 31 },
    quotes: [
      { symbol: "SPY", ref: 550.2, monday: 551.05, wednesday: 549.6, friday: 550.9 },
      { symbol: "QQQ", ref: 470.4, monday: 471.1, wednesday: 469.8, friday: 470.6 },
      { symbol: "IWM", ref: 211.5, monday: 212.2, wednesday: 210.9, friday: 211.7 },
      { symbol: "NVDA", ref: 119.4, monday: 120.1, wednesday: 118.7, friday: 119.8 },
      { symbol: "AAPL", ref: 221, monday: 221.8, wednesday: 220.4, friday: 221.3 },
      { symbol: "TLT", ref: 91.2, monday: 91.05, wednesday: 91.4, friday: 91.15 },
      { symbol: "MSFT", ref: 404.5, monday: 405.2, wednesday: 403.8, friday: 404.9 },
    ],
    calls: [
      {
        handle: "levellena",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Pin at 550–551. Long against 548, resistance 551.50, target a tag of 551.",
        levels: [
          target("SPY", 551),
          support("SPY", 549.5),
          resistance("SPY", 551.5),
          invalidation("SPY", 548),
        ],
      },
      {
        handle: "futuresfox",
        direction: "bearish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Fail at 551.50 and rotate back to 549. This is not a breakdown call. Stop 552.50.",
        levels: [target("SPY", 549), resistance("SPY", 551.5), invalidation("SPY", 552.5)],
      },
      {
        handle: "gapfade",
        direction: "bearish",
        conviction: "medium",
        primary: "QQQ",
        explicit: true,
        body: "Fade a Monday pop back to 470 on QQQ. Resistance 472. Wrong above 473.",
        levels: [target("QQQ", 470), resistance("QQQ", 472), invalidation("QQQ", 473)],
      },
      {
        handle: "permapump",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Consolidation, then markup. 560 is still the number. I am wrong under 545.",
        levels: [target("SPY", 560), invalidation("SPY", 545)],
      },
      {
        handle: "doomscroll",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "This calm is distribution. 530 is in play. I am wrong above 555.",
        levels: [target("SPY", 530), invalidation("SPY", 555)],
      },
      {
        handle: "nasdaqnun",
        direction: "bullish",
        conviction: "medium",
        primary: "NVDA",
        explicit: true,
        body: "NVDA bases and pushes 125. Leave it under 116.",
        levels: [target("NVDA", 125), invalidation("NVDA", 116)],
      },
      {
        handle: "macromoth",
        direction: "bearish",
        conviction: "medium",
        primary: "QQQ",
        explicit: true,
        body: "Leadership rolls. 460 QQQ if the pin breaks down. Invalid above 476.",
        levels: [target("QQQ", 460), invalidation("QQQ", 476)],
      },
      {
        handle: "narrativened",
        direction: "bearish",
        conviction: "low",
        primary: "SPY",
        explicit: false,
        body: "Something about this tape feels tired. I would not chase strength.",
      },
      {
        handle: "yieldyak",
        direction: "bullish",
        conviction: "medium",
        primary: "TLT",
        explicit: true,
        body: "Yields stall here. TLT back to 92. Out if 90.50 breaks.",
        levels: [target("TLT", 92), invalidation("TLT", 90.5)],
      },
      {
        handle: "smallcapsam",
        direction: "bullish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "IWM holds 210.50 and squeezes toward 214. Invalid under 209.",
        levels: [target("IWM", 214), support("IWM", 210.5), invalidation("IWM", 209)],
      },
      {
        handle: "volwidow",
        direction: "bearish",
        conviction: "low",
        primary: "SPY",
        explicit: true,
        body: "Realized stays dead, but a drift under 547 pays the hedge. Stop 553.",
        levels: [target("SPY", 547), invalidation("SPY", 553)],
      },
      {
        handle: "gammagoblin",
        direction: "bullish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Gamma pins, then releases higher toward 553. I am out under 549.",
        levels: [target("SPY", 553), invalidation("SPY", 549)],
      },
      {
        handle: "dividenddruid",
        direction: "bullish",
        conviction: "medium",
        primary: "AAPL",
        explicit: true,
        body: "Apple respects 220 and tags 223. I leave the add under 218.",
        levels: [target("AAPL", 223), support("AAPL", 220), invalidation("AAPL", 218)],
      },
      {
        handle: "creditcrab",
        direction: "bearish",
        conviction: "low",
        primary: "IWM",
        explicit: true,
        body: "No credit stress, but I do not want small-cap beta. 208 if it slips. Stop 214.",
        levels: [target("IWM", 208), invalidation("IWM", 214)],
      },
      {
        handle: "tapeworm",
        direction: "bullish",
        conviction: "medium",
        primary: "MSFT",
        explicit: true,
        body: "Microsoft is a 406 magnet. Long into that print, out through 402.",
        levels: [target("MSFT", 406), resistance("MSFT", 406.5), invalidation("MSFT", 402)],
      },
    ],
  },
  {
    slug: "2026-09-07",
    title: "Gap and fade",
    summary:
      "Monday looked like a breakout. Friday looked like a trap. Same calls, three grades.",
    monday: { year: 2026, month: 9, day: 7 },
    quotes: [
      { symbol: "SPY", ref: 552, monday: 558.4, wednesday: 554.1, friday: 546.8 },
      { symbol: "QQQ", ref: 472, monday: 479.5, wednesday: 474.2, friday: 466.4 },
      { symbol: "IWM", ref: 212.8, monday: 214.6, wednesday: 213.1, friday: 209.4 },
      { symbol: "NVDA", ref: 120.5, monday: 124.8, wednesday: 122.1, friday: 116.9 },
      { symbol: "AAPL", ref: 222.4, monday: 226.1, wednesday: 223.8, friday: 219.5 },
      { symbol: "TLT", ref: 91.3, monday: 90.6, wednesday: 91.1, friday: 92.4 },
      { symbol: "MSFT", ref: 406, monday: 412.4, wednesday: 408.2, friday: 401.1 },
    ],
    calls: [
      {
        handle: "permapump",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Breakout week. 565 SPY. I trail out only if 549 fails.",
        levels: [target("SPY", 565), invalidation("SPY", 549)],
      },
      {
        handle: "nasdaqnun",
        direction: "bullish",
        conviction: "high",
        primary: "NVDA",
        explicit: true,
        body: "NVDA clears 122 and runs 128. Megacaps lead. Wrong under 118.",
        levels: [target("NVDA", 128), invalidation("NVDA", 118)],
      },
      {
        handle: "gammagoblin",
        direction: "bullish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "Call wall lifts. QQQ 482 if Sunday night holds a bid. Cut under 470.",
        levels: [target("QQQ", 482), invalidation("QQQ", 470)],
      },
      {
        handle: "dividenddruid",
        direction: "bullish",
        conviction: "medium",
        primary: "AAPL",
        explicit: true,
        body: "Add Apple through the weekend. 221 holds, 228 is the ask. Leave under 218.",
        levels: [target("AAPL", 228), support("AAPL", 221), invalidation("AAPL", 218)],
      },
      {
        handle: "smallcapsam",
        direction: "bullish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "Breadth finally confirms. IWM 218. Invalid under 210.",
        levels: [target("IWM", 218), invalidation("IWM", 210)],
      },
      {
        handle: "tapeworm",
        direction: "bullish",
        conviction: "medium",
        primary: "MSFT",
        explicit: true,
        body: "Opening drive continuation. Microsoft 414. I am wrong under 404.",
        levels: [target("MSFT", 414), invalidation("MSFT", 404)],
      },
      {
        handle: "narrativened",
        direction: "bullish",
        conviction: "low",
        primary: "SPY",
        explicit: false,
        body: "Risk is on. Don't overthink it. The tape wants higher prices.",
      },
      {
        handle: "doomscroll",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "The gap is the trap. SPY 547, with 546 as the shelf. I cover only if 560 sticks.",
        levels: [target("SPY", 547), support("SPY", 546), invalidation("SPY", 560)],
      },
      {
        handle: "macromoth",
        direction: "bearish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "This is a squeeze, not a trend. QQQ back to 468. Wrong above 481.",
        levels: [target("QQQ", 468), invalidation("QQQ", 481)],
      },
      {
        handle: "levellena",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Fade into 559 resistance. Target 547, shelf 546, invalid through 561.",
        levels: [
          target("SPY", 547),
          support("SPY", 546),
          resistance("SPY", 559),
          invalidation("SPY", 561),
        ],
      },
      {
        handle: "futuresfox",
        direction: "bearish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Sell the reopen rip. 550 cash is the retrace. Stop 559.50.",
        levels: [target("SPY", 550), invalidation("SPY", 559.5)],
      },
      {
        handle: "gapfade",
        direction: "bearish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "Classic weekend gap fade. QQQ back through 471. Resistance 478. Stop 481.",
        levels: [target("QQQ", 471), resistance("QQQ", 478), invalidation("QQQ", 481)],
      },
      {
        handle: "volwidow",
        direction: "bearish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Own the downside. Spot to 549 is enough. Hedge dies above 560.",
        levels: [target("SPY", 549), invalidation("SPY", 560)],
      },
      {
        handle: "creditcrab",
        direction: "bearish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "Small caps will not hold a gap. 208 IWM. I am wrong above 216.",
        levels: [target("IWM", 208), invalidation("IWM", 216)],
      },
      {
        handle: "yieldyak",
        direction: "bullish",
        conviction: "medium",
        primary: "TLT",
        explicit: true,
        body: "If equities are gapping on fumes, bonds catch a bid toward 92.50. Cut 90.20.",
        levels: [target("TLT", 92.5), invalidation("TLT", 90.2)],
      },
    ],
  },
  {
    slug: "2026-09-14",
    title: "Quiet grind",
    summary:
      "No drama. Bullish books that named levels stayed right. The crash books did not get a second act.",
    monday: { year: 2026, month: 9, day: 14 },
    quotes: [
      { symbol: "SPY", ref: 547.5, monday: 550.2, wednesday: 553.8, friday: 556.4 },
      { symbol: "QQQ", ref: 467.2, monday: 470.4, wednesday: 474.1, friday: 477.6 },
      { symbol: "IWM", ref: 210.2, monday: 211.4, wednesday: 212.8, friday: 214.1 },
      { symbol: "NVDA", ref: 117.4, monday: 119.2, wednesday: 121.8, friday: 124.5 },
      { symbol: "AAPL", ref: 220.1, monday: 221.4, wednesday: 223.2, friday: 225 },
      { symbol: "TLT", ref: 92.2, monday: 91.8, wednesday: 91.3, friday: 90.9 },
      { symbol: "MSFT", ref: 402.4, monday: 405.1, wednesday: 408.4, friday: 411.2 },
    ],
    calls: [
      {
        handle: "nasdaqnun",
        direction: "bullish",
        conviction: "high",
        primary: "NVDA",
        explicit: true,
        body: "Back to trend. NVDA 124. Out below 115.",
        levels: [target("NVDA", 124), invalidation("NVDA", 115)],
      },
      {
        handle: "gammagoblin",
        direction: "bullish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "Dip gamma is long. QQQ 476. I leave it under 466.",
        levels: [target("QQQ", 476), invalidation("QQQ", 466)],
      },
      {
        handle: "permapump",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Always the same trade. SPY 558. Wrong under 544.",
        levels: [target("SPY", 558), invalidation("SPY", 544)],
      },
      {
        handle: "dividenddruid",
        direction: "bullish",
        conviction: "medium",
        primary: "AAPL",
        explicit: true,
        body: "Apple grinds to 225. 219 is the add. I am out under 216.",
        levels: [target("AAPL", 225), support("AAPL", 219), invalidation("AAPL", 216)],
      },
      {
        handle: "levellena",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Accept above 548. Target 555, supply at 556, invalid under 546.",
        levels: [
          target("SPY", 555),
          resistance("SPY", 556),
          invalidation("SPY", 546),
        ],
      },
      {
        handle: "futuresfox",
        direction: "bullish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Hold the Sunday settle and auction to 554. Cut under 546.50.",
        levels: [target("SPY", 554), invalidation("SPY", 546.5)],
      },
      {
        handle: "smallcapsam",
        direction: "bullish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "IWM participates this time. 214, with support at 209. Invalid under 207.",
        levels: [target("IWM", 214), support("IWM", 209), invalidation("IWM", 207)],
      },
      {
        handle: "tapeworm",
        direction: "bullish",
        conviction: "medium",
        primary: "MSFT",
        explicit: true,
        body: "Microsoft reclaim. Target 410. Wrong under 400.",
        levels: [target("MSFT", 410), invalidation("MSFT", 400)],
      },
      {
        handle: "yieldyak",
        direction: "bearish",
        conviction: "medium",
        primary: "TLT",
        explicit: true,
        body: "Stocks up, bonds down. TLT 91. I cover above 93.",
        levels: [target("TLT", 91), invalidation("TLT", 93)],
      },
      {
        handle: "doomscroll",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Last-chance short. 535, or I am done above 552.",
        levels: [target("SPY", 535), invalidation("SPY", 552)],
      },
      {
        handle: "macromoth",
        direction: "bearish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "Fade the grind. QQQ 458. Wrong above 473.",
        levels: [target("QQQ", 458), invalidation("QQQ", 473)],
      },
      {
        handle: "gapfade",
        direction: "bearish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Monday strength is a fade back to 546. Resistance 551. Stop 553.",
        levels: [target("SPY", 546), resistance("SPY", 551), invalidation("SPY", 553)],
      },
      {
        handle: "volwidow",
        direction: "bearish",
        conviction: "low",
        primary: "QQQ",
        explicit: true,
        body: "Hedge the grind. QQQ 465 pays for the puts. Hedge off above 475.",
        levels: [target("QQQ", 465), invalidation("QQQ", 475)],
      },
      {
        handle: "creditcrab",
        direction: "bullish",
        conviction: "low",
        primary: "SPY",
        explicit: true,
        body: "Not brave, just long the index into 552 with a tight line at 545.",
        levels: [target("SPY", 552), invalidation("SPY", 545)],
      },
      {
        handle: "narrativened",
        direction: "bullish",
        conviction: "medium",
        primary: "QQQ",
        explicit: false,
        body: "Tech wants to be bought. You can feel it in the timeline.",
      },
    ],
  },
  {
    slug: "2026-09-21",
    title: "Reopen bid",
    summary:
      "The newest cohort. Monday's initial grade is in. Wednesday and Friday are still on the clock.",
    monday: { year: 2026, month: 9, day: 21 },
    isLatest: true,
    quotes: [
      { symbol: "SPY", ref: 557, monday: 560.3, wednesday: null, friday: null },
      { symbol: "QQQ", ref: 478.4, monday: 481.9, wednesday: null, friday: null },
      { symbol: "IWM", ref: 214.6, monday: 215.4, wednesday: null, friday: null },
      { symbol: "NVDA", ref: 125.2, monday: 127.4, wednesday: null, friday: null },
      { symbol: "AAPL", ref: 225.4, monday: 226.8, wednesday: null, friday: null },
      { symbol: "TLT", ref: 90.7, monday: 90.2, wednesday: null, friday: null },
      { symbol: "MSFT", ref: 412, monday: 415.2, wednesday: null, friday: null },
    ],
    calls: [
      {
        handle: "levellena",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Sunday settle holds. Target 560, support 556, invalid under 553.",
        levels: [target("SPY", 560), support("SPY", 556), invalidation("SPY", 553)],
      },
      {
        handle: "futuresfox",
        direction: "bullish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Auction toward 561. Cut the long under 555.",
        levels: [target("SPY", 561), invalidation("SPY", 555)],
      },
      {
        handle: "nasdaqnun",
        direction: "bullish",
        conviction: "high",
        primary: "NVDA",
        explicit: true,
        body: "NVDA 130 this week. I am wrong under 122.",
        levels: [target("NVDA", 130), invalidation("NVDA", 122)],
      },
      {
        handle: "gammagoblin",
        direction: "bullish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "QQQ pushes 485 if the call wall stays bid. Out under 476.",
        levels: [target("QQQ", 485), invalidation("QQQ", 476)],
      },
      {
        handle: "permapump",
        direction: "bullish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "570. Same call as always. Only a break of 550 changes it.",
        levels: [target("SPY", 570), invalidation("SPY", 550)],
      },
      {
        handle: "dividenddruid",
        direction: "bullish",
        conviction: "medium",
        primary: "AAPL",
        explicit: true,
        body: "Apple holds 224 and works toward 228. I leave under 222.",
        levels: [target("AAPL", 228), support("AAPL", 224), invalidation("AAPL", 222)],
      },
      {
        handle: "smallcapsam",
        direction: "bullish",
        conviction: "medium",
        primary: "IWM",
        explicit: true,
        body: "Small caps tag along to 218. Invalid under 212.",
        levels: [target("IWM", 218), invalidation("IWM", 212)],
      },
      {
        handle: "tapeworm",
        direction: "bullish",
        conviction: "medium",
        primary: "MSFT",
        explicit: true,
        body: "Microsoft is a 416 print. I am wrong back through 410.",
        levels: [target("MSFT", 416), invalidation("MSFT", 410)],
      },
      {
        handle: "yieldyak",
        direction: "bearish",
        conviction: "medium",
        primary: "TLT",
        explicit: true,
        body: "The reopen bid leaks into bonds. TLT 89.50. Cover above 91.40.",
        levels: [target("TLT", 89.5), invalidation("TLT", 91.4)],
      },
      {
        handle: "doomscroll",
        direction: "bearish",
        conviction: "high",
        primary: "SPY",
        explicit: true,
        body: "Fade the reopen. SPY 548. I cover only if 561 sticks.",
        levels: [target("SPY", 548), invalidation("SPY", 561)],
      },
      {
        handle: "macromoth",
        direction: "bearish",
        conviction: "high",
        primary: "QQQ",
        explicit: true,
        body: "Leadership is tired. QQQ back to 470. Wrong above 483.",
        levels: [target("QQQ", 470), invalidation("QQQ", 483)],
      },
      {
        handle: "gapfade",
        direction: "bearish",
        conviction: "medium",
        primary: "SPY",
        explicit: true,
        body: "Fade the Monday bid back to 555. Resistance 559. Stop 562.",
        levels: [target("SPY", 555), resistance("SPY", 559), invalidation("SPY", 562)],
      },
      {
        handle: "volwidow",
        direction: "bearish",
        conviction: "low",
        primary: "QQQ",
        explicit: true,
        body: "Keep the hedge on. QQQ 476 is enough to pay for it. Off above 484.",
        levels: [target("QQQ", 476), invalidation("QQQ", 484)],
      },
      {
        handle: "creditcrab",
        direction: "bullish",
        conviction: "low",
        primary: "SPY",
        explicit: true,
        body: "Small long. Target 559, stop 554. Nothing heroic.",
        levels: [target("SPY", 559), invalidation("SPY", 554)],
      },
      {
        handle: "narrativened",
        direction: "bullish",
        conviction: "medium",
        primary: "SPY",
        explicit: false,
        body: "Bulls look in control again. I would not fade a tape that feels this firm.",
      },
    ],
  },
];
